import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[env]
TERM="screen-256color"

[window]
padding.x = 0
padding.y = 0
decorations="None"
opacity=0.99

[scrolling]
history=50000
multiplier=3

[font]
normal.family = "Agave Nerd Font Mono"
size=14
